### ISSUE TITLE
Optional preview button

### ISSUE THREAD

**Issue by smwcollege** [mryand/gutentolerance#3]
While we have also found that the preview button can be confusing for new editors, we cover it in our training and use it regularly.

For now, I'm just stripping the CSS out of the plugin, but do you think that could be an option/setting in future iterations of the plugin?

**Comment by mryand** [comment]
I've been meaning to add a settings page and start parameterizing things, so I'll start with that as the first option. You can see progress so far in the settings branch... not quite working yet.

**Comment by mryand** [comment]
This is resolved with the 1.0 release. You should now see an options page with a single option for now, controlling the display of the preview button.
